Repository SWYP3/Front-Dev, pull requests merged in 2024-07, with the labels that each got.

#5 [3] feat : 공통 변수 명 설정
  src/styles/_common.scss
  src/styles/_variables.scss
Labels: 🎨 UI

#7 Feature/6 : 공통 레이아웃 설정 및 공통 폰트 설정
  src/app/globals.scss
  src/app/layout.module.scss
  src/app/layout.tsx
  src/app/page.module.scss
  src/styles/reset.scss
Labels: 🎨 UI

#12 [Feature/8] 마이페이지 첫페이지 Ui 작업
  public/comment-icon.svg
  public/like-icon.svg
  public/post-icon.svg
  public/profile.svg
  public/right-icon.svg
  src/app/my-page/page.module.scss
  src/app/my-page/page.tsx
  src/components/common/Tab.module.scss
  src/components/common/Tab.tsx
Labels: 🛠️ 기능, 🎨 UI

#19 Feature/18 : 아이콘 추가
  public/record-icon.png
  public/tooth-icon.png
  src/app/my-page/page.module.scss
  src/app/my-page/page.tsx
Labels: 🎨 UI

#21 Feature/16 : 수정페이지(마이페이지)
  public/pencil.svg
  src/app/my-page/edit/page.module.scss
  src/app/my-page/edit/page.tsx
  src/styles/_variables.scss
Labels: 🎨 UI

#22 [2] feat : zustand 설치 및 tab 전역상태로 변경
  package-lock.json
  package.json
  src/app/my-page/page.tsx
  src/components/common/Tab.tsx
  src/context/Test.tsx
  src/stores/tab.ts
Labels: 🛠️ 기능

#25 [Feature/23] 나의 치아 페이지 구현
  public/tooth-back.svg
  public/tooth/bottom-1.svg
  public/tooth/bottom-2.svg
  public/tooth/bottom-3.svg
  public/tooth/bottom-4.svg
  public/tooth/bottom-5.svg
  public/tooth/bottom-6.svg
  public/tooth/bottom-7.svg
  public/tooth/colorTooth/bottom-1.svg
  public/tooth/colorTooth/bottom-2.svg
  public/tooth/colorTooth/bottom-3.svg
  public/tooth/colorTooth/bottom-4.svg
  public/tooth/colorTooth/bottom-5.svg
  public/tooth/colorTooth/bottom-6.svg
  public/tooth/colorTooth/bottom-7.svg
  public/tooth/colorTooth/top-1.svg
  public/tooth/colorTooth/top-2.svg
  public/tooth/colorTooth/top-3.svg
  public/tooth/colorTooth/top-4.svg
  public/tooth/colorTooth/top-5.svg
  public/tooth/colorTooth/top-6.svg
  public/tooth/colorTooth/top-7.svg
  public/tooth/top-1.svg
  public/tooth/top-2.svg
  public/tooth/top-3.svg
  public/tooth/top-4.svg
  public/tooth/top-5.svg
  public/tooth/top-6.svg
  public/tooth/top-7.svg
  src/app/my-page/history/page.module.scss
  src/app/my-page/history/page.tsx
  src/app/my-page/page.module.scss
  src/app/my-page/page.tsx
  src/app/my-page/tooth/page.module.scss
  src/app/my-page/tooth/page.tsx
  src/components/common/Header.module.scss
  src/components/common/PostCard.module.scss
  src/components/tooth/Tooth.module.scss
  src/components/tooth/Tooth.tsx
  src/constants/toothConstants.ts
  src/styles/_common.scss
Labels: 🛠️ 기능, 🎨 UI

#30 [29] feat : 공통 치료 변수 추가 및 공통 스와이프 구현
  package-lock.json
  package.json
  src/components/common/TreatmentSwiper.module.scss
  src/components/common/TreatmentSwiper.tsx
  src/constants/treatmentConstants.ts
Labels: 🛠️ 기능, ⚙️ Setting

#28 [Feature/26] 공통 모달 구현
  public/check-small.svg
  public/refresh.svg
  src/app/layout.module.scss
  src/app/my-page/edit/page.module.scss
  src/app/my-page/edit/page.tsx
  src/app/page.module.scss
  src/components/common/BtnBottom.module.scss
  src/components/common/BtnBottom.tsx
  src/components/common/Modal.module.scss
  src/components/common/Modal.tsx
  src/components/modal/DeleteModal.module.scss
  src/components/modal/DeleteModal.tsx
  src/components/modal/ToothWriteModal.module.scss
  src/components/modal/ToothWriteModal.tsx
  src/components/modal/TreatmentAddModal.module.scss
  src/components/modal/TreatmentAddModal.tsx
  src/components/modal/TreatmentModal.module.scss
  src/components/modal/TreatmentModal.tsx
  src/stores/modal.ts
  src/styles/_common.scss
Labels: 🛠️ 기능, 🎨 UI

#27 [15] feat : 영역 수정 및 디폴트 이미지 수정
  public/image-default.png
  public/image-default.svg
  public/post-default.png
  src/components/common/PostCard.module.scss
  src/components/common/PostCard.tsx
Labels: 🎨 UI

#32 [16] feat : 이메일 길 때 레이아웃 조정
  src/app/my-page/edit/page.module.scss
Labels: 🎨 UI

#34 [Feature/33] 커뮤니티 리스트 ui 구현
  public/delete-icon.svg
  public/new-notice.svg
  public/no-search-word.png
  public/no-search.png
  public/notice.svg
  public/search-icon.svg
  src/app/community/page.module.scss
  src/app/community/page.tsx
  src/app/my-page/page.module.scss
  src/components/common/PostCard.module.scss
  src/components/common/PostCard.tsx
  src/components/common/Tab.module.scss
  src/components/community/NoSearchData.module.scss
  src/components/community/NoSearchData.tsx
  src/styles/_variables.scss
Labels: 🛠️ 기능, 🎨 UI

#37 [Feature/35] 첫 진입페이지 구현
  package-lock.json
  package.json
  public/main/google.png
  public/main/logo-img.png
  public/main/logo-text.png
  public/main/main-bottom.svg
  public/main/main-top.png
  public/spinner.gif
  public/welcome/check.svg
  public/welcome/click.png
  public/welcome/cursor.png
  public/welcome/first.png
  public/welcome/next-button.svg
  public/welcome/second-back.png
  public/welcome/second-bottom.png
  public/welcome/second-mid.png
  public/welcome/second-top.png
  public/welcome/third.png
  src/app/globals.scss
  src/app/loading.module.scss
  src/app/loading.tsx
  src/app/page.module.scss
  src/app/page.tsx
  src/app/welcome/login/page.module.scss
  src/app/welcome/login/page.tsx
  src/app/welcome/page.module.scss
  src/app/welcome/page.tsx
  src/components/motion/ScaleButton.module.scss
  src/components/motion/ScaleButton.tsx
  src/components/welcome/OnBoarding.module.scss
  src/components/welcome/OnBoarding.tsx
Labels: 🛠️ 기능, 🎨 UI

#40 [Feature/39] 달력 커스텀 작업
  package-lock.json
  package.json
  public/date-icon.svg
  public/default-tooth.png
  public/location_on.svg
  public/next.svg
  src/app/medical/page.module.scss
  src/app/medical/page.tsx
  src/app/medical/write/page.module.scss
  src/app/medical/write/page.tsx
  src/components/common/CustomCalendar.tsx
  src/components/common/TreatmentSwiper.module.scss
  src/components/medical/ClinicInput.module.scss
  src/components/medical/ClinicInput.tsx
  src/components/medical/CostInput.module.scss
  src/components/medical/CostInput.tsx
  src/components/medical/DateInput.module.scss
  src/components/medical/DateInput.tsx
  src/components/medical/MedicalWrite.module.scss
  src/components/medical/MedicalWrite.tsx
  src/components/medical/ShareOption.module.scss
  src/components/medical/ShareOption.tsx
  src/components/medical/ToothSelection.module.scss
  src/components/medical/ToothSelection.tsx
  src/components/medical/TreatmentSelection.module.scss
  src/components/medical/TreatmentSelection.tsx
  src/styles/CustomCalendar.css
  src/styles/_common.scss
  src/styles/_variables.scss
  src/styles/reset.scss
Labels: 🛠️ 기능, 🎨 UI

#45 [Feature/42] 치아관련 진료기록 내용 입력 부분 구현
  public/delete-input-icon.svg
  src/components/common/Modal.tsx
  src/components/medical/CostInput.module.scss
  src/components/medical/CostInput.tsx
  src/components/medical/MedicalWrite.tsx
  src/components/medical/ToothSelection.tsx
  src/components/medical/TreatmentSelection.tsx
  src/components/modal/Modal.module.scss
  src/components/modal/Modal.tsx
  src/components/modal/ToothWriteModal.module.scss
  src/components/modal/ToothWriteModal.tsx
  src/components/modal/TreatmentAddModal.module.scss
  src/components/modal/TreatmentAddModal.tsx
  src/components/tooth/Tooth.tsx
  src/constants/toothConstants.ts
  src/stores/medicalWrite.ts
  src/stores/modal.ts
  src/styles/CustomCalendar.css
Labels: 🛠️ 기능, 🎨 UI

#44 [Feature/43] 게시글 작성하기 ui
  public/image-add.svg
  src/app/community/write/page.module.scss
  src/app/community/write/page.tsx
  src/components/common/ImageSwiper.tsx
  src/components/common/imageSwiper.module.scss
Labels: 🛠️ 기능, 🎨 UI

#49 Feature/48
  next.config.mjs
  src/app/my-page/page.module.scss
  src/app/my-page/page.tsx
  src/app/my-page/terms/page.module.scss
  src/app/my-page/terms/page.tsx
  src/components/modal/ AccountActionModal.tsx
  src/components/modal/AccountActionModal.module.scss
  src/components/mypage/Service.tsx
  src/components/mypage/UserProfileCard.module.scss
  src/components/mypage/UserProfileCard.tsx
Labels: 🛠️ 기능, 🎨 UI

#52 Feature/50
  next.config.mjs
  package-lock.json
  package.json
  public/caret-up.svg
  src/api/medicalRecord.ts
  src/app/my-page/page.module.scss
  src/app/my-page/page.tsx
  src/app/my-page/terms/page.module.scss
  src/app/my-page/terms/page.tsx
  src/components/common/CustomCalendar.tsx
  src/components/common/Highlight.module.scss
  src/components/common/Higtlight.tsx
  src/components/medical/ClinicInput.module.scss
  src/components/medical/ClinicInput.tsx
  src/components/medical/DateInput.module.scss
  src/components/medical/DateInput.tsx
  src/components/modal/ AccountActionModal.tsx
  src/components/modal/AccountActionModal.module.scss
  src/components/mypage/Service.tsx
  src/components/mypage/UserProfileCard.module.scss
  src/components/mypage/UserProfileCard.tsx
  src/styles/_common.scss
  src/util/formatDate.ts
Labels: 🛠️ 기능, 🎨 UI

#54 feat : 커뮤니티 ui
  src/app/community/post/[id]/page.module.scss
  src/app/community/post/[id]/page.tsx
  src/app/community/write/page.tsx
  src/components/common/ImageSwiper.tsx
  src/components/common/imageSwiper.module.scss
Labels: 🛠️ 기능, 🎨 UI

#59 Feature/56
  public/no-search-record.png
  public/scroll-up.svg
  src/api/axiosApi/axiosServer.ts
  src/api/medical.ts
  src/api/medicalRecord.ts
  src/app/community/page.tsx
  src/app/medical/detail/[id]/page.module.scss
  src/app/medical/detail/[id]/page.tsx
  src/app/medical/page.tsx
  src/app/my-page/history/page.tsx
  src/components/common/BtnBottom.tsx
  src/components/common/Header.tsx
  src/components/common/HistoryCard.module.scss
  src/components/common/HistoryCard.tsx
  src/components/common/ScrollToTop.module.scss
  src/components/common/ScrollToTop.tsx
  src/components/medical/CostInput.tsx
  src/components/medical/DetailActionButton.module.scss
  src/components/medical/DetailActionButton.tsx
  src/components/medical/MedicalContent.module.scss
  src/components/medical/MedicalContent.tsx
  src/components/medical/MedicalWrite.tsx
  src/components/medical/ToothSelection.module.scss
  src/components/medical/ToothSelection.tsx
  src/components/medical/UserWelcome.tsx
  src/components/modal/DeleteModal.tsx
  src/components/modal/TreatmentModal.tsx
  src/components/noData/NoSearchData.module.scss
  src/components/noData/NoSearchData.tsx
  src/components/tooth/DetailTooth.module.scss
  src/components/tooth/DetailTooth.tsx
  src/components/tooth/Tooth.tsx
  src/components/tooth/ToothSelectSection.module.scss
  src/components/tooth/ToothSelectSection.tsx
  src/stores/medicalWrite.ts
  src/stores/tooth.ts
  src/util/findTooth.ts
Labels: 🛠️ 기능

#57 [Feature/43] 삭제 ui 구현
  public/trashCan-icon.svg
  src/app/community/post/[id]/page.module.scss
  src/app/community/post/[id]/page.tsx
Labels: 🎨 UI

#61 Feature/60
  package-lock.json
  package.json
  src/api/axiosApi/axiosInstance.ts
  src/api/medical.ts
  src/api/medicalRecord.ts
  src/app/medical/detail/[id]/page.tsx
  src/components/common/HistoryCard.module.scss
  src/components/common/HistoryCard.tsx
  src/components/medical/ClinicInput.tsx
  src/components/medical/CostInput.tsx
  src/components/medical/DateInput.tsx
  src/components/medical/DetailActionButton.tsx
  src/components/medical/MedicalContent.tsx
  src/components/medical/MedicalWrite.tsx
  src/components/medical/ShareOption.tsx
  src/components/medical/ToothSelection.tsx
  src/components/medical/TreatmentSelection.tsx
  src/components/modal/DeleteModal.tsx
  src/components/modal/SimpleModal.tsx
  src/components/modal/TreatmentModal.tsx
  src/components/tooth/DetailTooth.tsx
  src/stores/medicalWrite.ts
  src/util/formatData.ts
Labels: 🛠️ 기능

#62 Feature/58
  public/pencil-black.svg
  src/api/communityApi.ts
  src/app/community/page.module.scss
  src/app/community/page.tsx
  src/app/community/post/[id]/page.tsx
  src/app/community/write/page.module.scss
  src/app/community/write/page.tsx
  src/components/common/ImageSwiper.tsx
  src/components/common/PostCard.tsx
  src/components/common/TreatmentSwiper.tsx
  src/components/modal/SimpleModal.tsx
  src/constants/treatmentConstants.ts
  src/util/formatDate.ts
Labels: 🛠️ 기능, 🎨 UI

#64 Feature/63
  src/api/communityApi.ts
  src/app/community/page.module.scss
  src/app/community/page.tsx
  src/app/community/post/[id]/page.module.scss
  src/app/community/post/[id]/page.tsx
  src/components/common/PostCard.module.scss
  src/components/common/PostCard.tsx
  src/components/common/TreatmentSwiper.tsx
Labels: 🛠️ 기능, 🎨 UI

#67 Feature/63
  src/api/communityApi.ts
  src/app/community/page.tsx
  src/app/community/post/[id]/page.module.scss
  src/app/community/post/[id]/page.tsx
  src/app/community/write/page.tsx
  src/components/common/PostCard.module.scss
  src/components/common/PostCard.tsx
  src/components/common/imageSwiper.module.scss
  src/components/modal/SimpleModal.tsx
Labels: 🛠️ 기능, 🎨 UI

#71 Feature/70
  next.config.mjs
  src/api/medicalRecord.ts
  src/api/myPage.ts
  src/app/layout.module.scss
  src/app/layout.tsx
  src/app/loading.module.scss
  src/app/my-activity/[type]/page.tsx
  src/app/my-page/history/page.tsx
  src/app/my-page/page.module.scss
  src/app/my-page/page.tsx
  src/components/common/HistoryCard.tsx
  src/components/common/LoadingSpinner.module.scss
  src/components/common/LoadingSpinner.tsx
  src/components/common/MyPostCard.module.scss
  src/components/common/MyPostCard.tsx
  src/components/medical/ClinicInput.module.scss
  src/components/medical/ClinicInput.tsx
  src/components/medical/CostInput.tsx
  src/components/medical/DateInput.tsx
  src/components/medical/MedicalContent.tsx
  src/components/medical/UserWelcome.tsx
  src/components/mypage/Service.module.scss
  src/hook/useInfiniteScroll.tsx
Labels: 🛠️ 기능, 🎨 UI

#75 Feature/72
  src/api/communityApi.ts
  src/api/myPage.ts
  src/app/community/notice/page.module.scss
  src/app/community/notice/page.tsx
  src/app/my-activity/[type]/page.tsx
  src/app/my-page/page.tsx
  src/components/common/HistoryCard.tsx
  src/components/common/MyPostCard.tsx
  src/components/medical/ClinicInput.tsx
  src/components/medical/CostInput.tsx
  src/components/medical/DateInput.tsx
  src/components/medical/MedicalContent.module.scss
  src/components/medical/MedicalContent.tsx
  src/components/medical/MedicalWrite.tsx
  src/components/medical/ToothSelection.tsx
  src/components/medical/TreatmentSelection.tsx
  src/components/medical/UserWelcome.tsx
  src/components/modal/TreatmentMyModal.module.scss
  src/components/mypage/Service.tsx
  src/stores/medicalWrite.ts
  src/stores/tooth.ts
  src/styles/_variables.scss
  src/util/validation.ts
Labels: 🛠️ 기능, 🎨 UI

#76 Feature/74
  public/default-post.png
  public/default-postin.png
  src/api/communityApi.ts
  src/app/community/page.tsx
  src/app/community/post/[id]/page.module.scss
  src/app/community/post/[id]/page.tsx
  src/app/community/write/page.tsx
  src/components/common/ImageSwiper.tsx
  src/components/common/PostCard.module.scss
  src/components/common/PostCard.tsx
  src/components/common/imageSwiper.module.scss
  src/components/modal/DeleteModal.tsx
  src/components/modal/SimpleModal.tsx
  src/util/formatDate.ts
Labels: 🛠️ 기능, 🎨 UI

#79 feat : 마이프로필 이미지 주소 수정
  src/app/community/write/page.tsx
  src/app/my-page/edit/page.tsx
  src/components/common/ImageSwiper.tsx
  src/components/modal/DeleteModal.tsx
  src/components/mypage/UserProfileCard.tsx
Labels: 🛠️ 기능, 🐛버그

#81 feat : 프로필카드 주소 설정
  src/components/common/HistoryCard.tsx
Labels: 🛠️ 기능, 🐛버그

#82 feat : refetch 조정 작업
  src/app/community/page.tsx
Labels: 🛠️ 기능, 🐛버그

#85 Feature/84
  next.config.mjs
  src/api/axiosApi/axiosInstance.ts
  src/app/community/post/[id]/page.tsx
  src/components/common/PostCard.tsx
Labels: 🛠️ 기능, 🐛버그

#86 feat : 커뮤니티 가로스크롤 방지
  src/components/common/PostCard.module.scss
Labels: 🐛버그, 🎨 UI
